- hosts:  web 
  remote_user: root
  become: yes
  tasks:
  - name: Install Apache 
    yum:
      name: httpd
      state: installed 
  - name: Restart Apache 
    yum: 
      name: htppd
      state: restarted 
  - name: Remove Apache 
    yum:
      name: httpd
      state: remove 





